/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQuerySwiftsampleapi.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API
// Classes:
//   GTLQuerySwiftsampleapi (2 custom class methods, 1 custom properties)

#import "GTLQuerySwiftsampleapi.h"

#import "GTLSwiftsampleapiGetRes.h"
#import "GTLSwiftsampleapiPostReq.h"
#import "GTLSwiftsampleapiPostRes.h"

@implementation GTLQuerySwiftsampleapi

@dynamic fields;

#pragma mark -
#pragma mark "message" methods
// These create a GTLQuerySwiftsampleapi object.

+ (id)queryForMessageGet {
  NSString *methodName = @"swiftsampleapi.message.get";
  GTLQuerySwiftsampleapi *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLSwiftsampleapiGetRes class];
  return query;
}

+ (id)queryForMessagePostWithObject:(GTLSwiftsampleapiPostReq *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"swiftsampleapi.message.post";
  GTLQuerySwiftsampleapi *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLSwiftsampleapiPostRes class];
  return query;
}

@end
