/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQuerySwiftsampleapi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API
// Classes:
//   GTLQuerySwiftsampleapi (2 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLSwiftsampleapiPostReq;

@interface GTLQuerySwiftsampleapi : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark "message" methods
// These create a GTLQuerySwiftsampleapi object.

// Method: swiftsampleapi.message.get
// Get greeting
// Fetches a GTLSwiftsampleapiGetRes.
+ (id)queryForMessageGet;

// Method: swiftsampleapi.message.post
// Post greeting
//  Authorization scope(s):
//   kGTLAuthScopeSwiftsampleapiUserinfoEmail
// Fetches a GTLSwiftsampleapiPostRes.
+ (id)queryForMessagePostWithObject:(GTLSwiftsampleapiPostReq *)object;

@end
