/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSwiftsampleapiGetRes.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API
// Classes:
//   GTLSwiftsampleapiGetRes (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSwiftsampleapiGetRes
//

@interface GTLSwiftsampleapiGetRes : GTLObject
@property (copy) NSString *message;
@end
