/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSwiftsampleapiPostRes.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API
// Classes:
//   GTLSwiftsampleapiPostRes (0 custom class methods, 4 custom properties)

#import "GTLSwiftsampleapiPostRes.h"

// ----------------------------------------------------------------------------
//
//   GTLSwiftsampleapiPostRes
//

@implementation GTLSwiftsampleapiPostRes
@dynamic email, identifier, message, registeredAt;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
