/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSwiftsampleapi_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API

#import "GTLSwiftsampleapiConstants.m"

#import "GTLSwiftsampleapiGetRes.m"
#import "GTLSwiftsampleapiPostReq.m"
#import "GTLSwiftsampleapiPostRes.m"

#import "GTLQuerySwiftsampleapi.m"
#import "GTLServiceSwiftsampleapi.m"
