/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSwiftsampleapi.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API

#import "GTLSwiftsampleapiConstants.h"

#import "GTLSwiftsampleapiGetRes.h"
#import "GTLSwiftsampleapiPostReq.h"
#import "GTLSwiftsampleapiPostRes.h"

#import "GTLQuerySwiftsampleapi.h"
#import "GTLServiceSwiftsampleapi.h"
