/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSwiftsampleapiPostReq.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API
// Classes:
//   GTLSwiftsampleapiPostReq (0 custom class methods, 1 custom properties)

#import "GTLSwiftsampleapiPostReq.h"

// ----------------------------------------------------------------------------
//
//   GTLSwiftsampleapiPostReq
//

@implementation GTLSwiftsampleapiPostReq
@dynamic message;
@end
