/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLSwiftsampleapiConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   swiftsampleapi/v1
// Description:
//   Swift Sample API

#import "GTLSwiftsampleapiConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSwiftsampleapiUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
